### ISSUE TITLE
Remove wrapped values and data processing from client.py

### ISSUE THREAD

**Issue by g-k** [mozilla/frost#11]
refs: https://github.com/mozilla-services/pytest-services/pull/9

The client wrapping results creates extra lists in `extract_key` and other methods and is a weird non-pythonic API to learn.

A library of helper functions would be clearer and more explicit.

**Comment by g-k** [comment]
@ajvb what do you think?

**Comment by ajvb** [comment]
@g-k This is interesting. I do agree with you that it's not very pythonic, but at the same time I like the API you created within `BotocoreClient`. It could probably be made more "friendly" though.

**Comment by g-k** [comment]
@ajvb If you get a chance to write something up, I'd be interested in how to make it more friendly. I think there are libraries for managing wrapped things or we stick things in a pandas dataframe.

**Comment by g-k** [comment]
Something that behaves like lenses or zippers from FP might be good fit though wouldn't be pythonic.

**Comment by ajvb** [comment]
👍 - I'm not really sure how to make it more friendly, which really means I'm not sure how to restructure the abstraction layer to get rid of the wrapped values. The current `extract_key`, `flatten`, `values` work flow is really nice and flexible once I understood it. Don't have much experience using dataframes in pandas so no opinion there.

**Comment by ajvb** [comment]
The current model has been working great now for almost 3 years. I'm going to close this for now, can re-open if we want to address this again in the future.
