### ISSUE TITLE
Allow pytest-services to be pip installed via PyPI

### ISSUE THREAD

**Issue by JohnVonNeumann** [mozilla/frost#113]
I would assume there to be obvious benefits in this, if entirely possible I wouldn't mind being able to just install this the way I'd install my other packages, without really caring about your dependencies.

**Comment by hwine** [comment]
I'm not sure how this would work. The entire repo is required - there aren't any executables or libraries to include elsewhere. It is not a Python package or module at present.

Can you describe the usage scenario you envision? I.e. what are you doing after the ``pip install``?

**Comment by g-k** [comment]
Hey @JohnVonNeumann, thanks for checking this out!

For now, the easiest way to run these would be to clone the repo, add a config, and run the tests you're interested in.

We originally planned to refactor this into pytest plugins (#3 and #4) and still might do that, but as Hal pointed out we decided to open source it as a bunch pytests for now.

The plugin based workflow would might look like:

1. have a pytest unit tests for you python application
1. add relevant pytest-services plugins as pip-installeable packages for your cloud provider, OS, monitoring services, etc. 
1. test them in CI or AWS config

Is that the kind of scenario you had in mind?
