### ISSUE TITLE
document adding a new service

### ISSUE THREAD

**Issue by g-k** [mozilla/frost#116]

**Comment by hwine** [comment]
I'll set this up as a normal rst -> sphinx -> readthedocs doc set unless someone hollers _REAL_ loud.

**Comment by g-k** [comment]
> I'll set this up as a normal rst -> sphinx -> readthedocs doc set unless someone hollers REAL loud.

👍  yeah, we've just been throwing everything in the readme, but that'd be best since this is a python project.

**Comment by hwine** [comment]
> since this is a python project.

pshaw -- Firefox is [documented](https://github.com/mozilla/gecko-dev/search?q=filename%3A*.rst) in sphinx! 😉

**Comment by ajvb** [comment]
@hwine looks good. May want to call out that you are not creating a new `conftest.py`, but editing the one at the top level of the repo.

**Comment by ajvb** [comment]
I believe this is done?

**Comment by hwine** [comment]
Yes -- this issue was satisfied by #318, and docs are at https://mozilla.github.io/frost/_build/html/index.html
