### ISSUE TITLE
Agree on persistent caching pattern

### ISSUE THREAD

**Issue by hwine** [mozilla/frost#117]
Some systems, notably GitHub, take significant time (hours) to acquire all the base data. For that reason,  it would be good to have a way to persist the cache between runs.

To Do:
- [x] Propose strategy
- [ ] Get agreement
- [ ] Implement (in GitHub)

**Comment by g-k** [comment]
@hwine sounds good! +1 on per service caches (didn't realize you could do per directory cachedirs but that makes sense) and mounting the directory. This would also fix #2 (e.g. by running `rm .cache/v/aws/iam` first).

In general I'm not super happy about having pytest fetch data directly. The main motivation for doing that was to not fetch any more data than the test required. We should be able to decouple the API clients and pytest.

Some other things that might be good to update with our caching:

* content addressable hashes (e.g. sha256 of data to cache). The downside is it would be less clear what's in the cache, but it would fix the cache key escaping nonsense (and file name too long errors) and https://github.com/mozilla-services/pytest-services/issues/105 too assuming the AWS profile or ARN shows up somewhere in the data to cache. 
* fs file limit workarounds e.g. using the first two chars of hash as a subdirectory git-style
* fix the bug where deserialized datetimes read from cache were not `datetime.datetime`'s like they are in when fetched uncached

**Comment by ajvb** [comment]
+1 to all of this.

I think it would also be nice to add the ability to **not cache** during a pytest run. The production runs for AWS always bust the cache and it would be made faster if they didn't write a bunch of stuff to disk unnecessarily

>In general I'm not super happy about having pytest fetch data directly.

I don't disagree with this, but what is the alternative?

**Comment by g-k** [comment]
> to add the ability to not cache during a pytest run

I thought we had a flag for that, but that'd be easy to add.

In general, it'd be good to decouple reading and writing from cache too e.g. so we could mount github data from one directory as read only then write it to a different directory and only update the cache if the fetching succeeds.

> the alternative?

Have separate scripts that receive or prefetch data to populate the cache first or define a protocol for tests to say "I want this data" and have those scripts or services fetch it or both.

**Comment by ajvb** [comment]
>I thought we had a flag for that, but that'd be easy to add.
>
>In general, it'd be good to decouple reading and writing from cache too e.g. so we could mount github data from one directory as read only then write it to a different directory and only update the cache if the fetching succeeds.

+1

>Have separate scripts that receive or prefetch data to populate the cache first or define a protocol for tests to say "I want this data" and have those scripts or services fetch it or both.
>
>+1 for a separate data fetch run. In addition to other benefits, it narrows the window of the snapshot, reducing the chance for things to change and appear inconsistent.

If we are using the model of capturing events and persisting them via webhooks or similar, then I very much agree with this. For github, or any service where it takes "a long time" to fetch the data, this also makes perfect sense.

For test suites like aws, gcp, and gsuite, I'm impartial. The window is very short and besides locally testing `resources` functions, I don't think the separation would be used any within the context of `pytest-services`. At the same time, if it is cleaner to do it for all services, no reason not to do so.

**Comment by hwine** [comment]
Updating with my current approach for GitHub.
a) The metrics collection pipeline does the heavy lifting, and uploads files to S3.
b) The driving framework for the docker run downloads needed files from S3 to the "results" directory
c) The ``results`` directory is mounted to the docker container.

**Comment by g-k** [comment]
hashfs https://github.com/dgilland/hashfs is an option

**Comment by g-k** [comment]
or using the AWS config API if that's enabled

**Comment by ajvb** [comment]
So, this issue is now pretty out of date. For AWS and GCP, the data fetching will stay where it is for now and the use of the pytest cache within the clients is working fine. Alternatives have been explored, but this seemed to work the best.

Additionally, the current caching strategy is described in our documentation: https://github.com/mozilla/frost/blob/master/docs/Architecture.rst#caching

Closing for now.
