### ISSUE TITLE
docker security checks

### ISSUE THREAD

**Issue by g-k** [mozilla/frost#121]
Check we're using trusted images, official images, or images someone has reviewed and signed off on.

https://docs.docker.com/engine/security/security/
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

Also, check against any insecure image registries.

**Comment by g-k** [comment]
@hwine pointed out https://techbeacon.com/10-top-open-source-tools-docker-security too

**Comment by hwine** [comment]
> images ... signed off on

fwiw, looks that could be formalized, even in CE: [Docker Trust](https://docs.docker.com/engine/security/trust/content_trust/)

Not sure if that effort is warranted.

**Comment by ajvb** [comment]
This seems like a potentially helpful tool: https://github.com/docker/docker-bench-security

**Comment by ajvb** [comment]
@g-k Same here, cool if I close this?

**Comment by g-k** [comment]
Yep!

**Comment by hwine** [comment]
This issue closed as not being appropriate for this repo. There is a [related (private) issue](https://github.com/mozilla-services/foxsec/issues/1695) that is a better place for further discussion.
