### ISSUE TITLE
CIS OS Benchmark checks

### ISSUE THREAD

**Issue by g-k** [mozilla/frost#122]
Check that our baked AMIs and base docker images against the CIS benchmarks for the OS.

e.g. for CentOS

https://security.uri.edu/files/CIS_CentOS_Linux_7_Benchmark_v1.1.01.pdf
https://nvd.nist.gov/ncp/checklist/500

**Comment by ajvb** [comment]
@g-k Cool if I close this one? Don't think we want to support this atm.

**Comment by g-k** [comment]
Yep
