### ISSUE TITLE
First pass of IAM tests from CIS Benchmarks

### ISSUE THREAD

**Issue by ajvb** [mozilla/frost#16]
[AWS CIS Benchmarks](https://d0.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf)

Implement tests for:
- ~1.4 Ensure access keys are rotated every 90 days or less~
- 1.9 Ensure IAM password policy requires minimum length of 14 or greater 
- 1.12 Ensure no root account access key exists

**Comment by jvehent** [comment]
key rotations every 90 days is nuts. I'd be happy to start with 2 years, and gradually work our way to one year.

**Comment by ajvb** [comment]
@jvehent 👍 - in that case I say we just don't test for it yet. After all of the current tests are passing can do another pass through of tests to add.
