### ISSUE TITLE
Come up with a better name

### ISSUE THREAD

**Issue by ajvb** [mozilla/frost#26]
3-5 letters

**Comment by g-k** [comment]
Also, the name should not imply that everything is on fire.

**Comment by jvehent** [comment]
![fire](https://78.media.tumblr.com/e0fb9ac5a6e89353044886c2eaaa9e76/tumblr_inline_mxccxpBTzk1qcryb6.gif)

**Comment by g-k** [comment]
bobm recommended "Loup Garou" which we could expose as `loup-garou` and maybe a `rougarou` alias.

The description is apt:

> most often is described as a creature with a human body and the head of a wolf or dog, similar to the werewolf legend. ... story-telling has been used to inspire fear and obedience. One such example is stories that have been told by elders to persuade Cajun children to behave.

https://en.wikipedia.org/wiki/Rougarou

pronunciation in: https://ia800606.us.archive.org/15/items/OTRR_Escape_Singles/Escape_52-11-16_-157-_The_Loup-Garou.mp3

I see 60 repos on github containing loup or garou, but none with more than 2 stars https://github.com/search?utf8=%E2%9C%93&q=loup-garou&type=

https://encrypted.google.com/search?hl=en&q=loup%2Dgarou%20software

https://github.com/search?utf8=%E2%9C%93&q=Rougarou&type=

So it looks like a good option.

**Comment by g-k** [comment]
^ not 3-5 letters unless we shorten it to loup or garou

**Comment by ajvb** [comment]
+1 to `rougarou` (as to not have a `-` in the name)

**Comment by ajvb** [comment]
My real vote is for `tif` though

**Comment by webknjaz** [comment]
FTR this also collapses with another (and older) lib with the same name: https://github.com/pytest-dev/pytest-services

**Comment by jvehent** [comment]
`frost`, for **F**i**r**efox **O**perations **S**ecurity **T**esting.
