### ISSUE TITLE
Testing SCPs

### ISSUE THREAD

**Issue by EmFl** [mozilla/frost#298]
Hello,
This is a question not an issue sorry if this is the wrong place to post this.

I'm wondering if I could use frost to test SCPs as part of our CI pipeline, the goal is to make sure we can still do a list of actions once we modify an SCP. I initially thought I could use iam policy simulator, however this tool is incompatible with some SCPs (for example region locking). AWS Support told me that my best option was to do actual calls to AWS so I need to create resources in a test account and then delete them. As far as I can see, frost is only doing reads at this point, I'm wondering if it could easily be used to do what I need (so handle creation/cleanup). Or if I should just use boto3/pytest outside of frost to handle this.
Thanks

**Comment by ajvb** [comment]
@EmFl that is a good question. Depending on what you mean by "SCPs", I think that the actual verification test could live in frost, but the creation/cleanup would probably need to live outside of frost.

**Comment by EmFl** [comment]
Hey,

SCP as in Service Control Policies (https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scp.html)
They are policies that allow organization administrator to block access to some resources/services on multiple AWS accounts. Even if you're admin of the account, SCP has the advantage.

Today I'm creating and pushing the SCP via my CI, but I'd like to test post deployment that all mandatory actions are still allowed (and some are still denied).
Sequence would be something like :

Write SCP > Commit > Push SCP to OU > (with frost ?) start test, for example, create an s3 bucket in eu-west-1 and us-east-1. Create an ec2 in both region etc. > If success, done, else, rollback.

Hope it makes more sense.

**Comment by ajvb** [comment]
@EmFl Ok thank you for the further explanation.

Thinking more about it, I think that this could work well within frost as long as there is a protection against users accidentally running this test (i.e. by running all aws tests with `pytest aws/*`). My thought is that there would be some sort of required additional CLI flag to pass to pytest (added here https://github.com/mozilla/frost/blob/fb0b5a3a53c24eb73c90b03309626b9bbe198569/conftest.py#L23-L64) that would enabled a "write mode" of sorts.
