### ISSUE TITLE
Configure tox for local use against multiple python versions

### ISSUE THREAD

**Issue by hwine** [mozilla/frost#308]
At this moment, that would be Python 3.6 & 3.8. In general it would be min_version..highest_GA_release

An open question is how/when to introduce the next GA release (i.e. version in beta), which is why I have not yet included "switch to tox for CI" in this issue.

**Comment by g-k** [comment]
Closing since AJ says we're entirely on 3.8 now and I updated setup.py to reflect that.

I don't think we should try to support more python versions unless we have to migrate again.

**Comment by hwine** [comment]
/me will bring up the other benefits of tox in a different issue :D
