### ISSUE TITLE
Replace deprecated oauth2lib library

### ISSUE THREAD

**Issue by hwine** [mozilla/frost#353]
The OAuth library in use ([oauth2lib](https://pypi.org/project/oauth2client/4.1.3/)) is depricated, and has not received any updates since [2018-09-20](https://github.com/googleapis/oauth2client)

The suggested replacements are [google-auth](https://google-auth.readthedocs.io/) and [oauthlib](http://oauthlib.readthedocs.io/), but those recommendations are 2 years old.

To do:
- [ ] find a still supported library that is up to snuff
- [ ] integrate it

**Comment by g-k** [comment]
Went with `google-auth` for the GCP bits of https://github.com/mozilla-services/takeonme/

Potentially useful links:

* https://googleapis.dev/python/google-auth/latest/user-guide.html#obtaining-credentials
* https://googleapis.dev/python/google-auth/latest/oauth2client-deprecation.html

**Comment by hwine** [comment]
If I understand correctly, `google-auth` only works for GCP at this point.

Do we have anything on the roadmap that might need to use oauth outside of GCP? E.g IAM/cis? (I'm unsure yet if I'll need to for frost, but may need to for `alert manager`.)
