### ISSUE TITLE
Running frost from docker image fails

### ISSUE THREAD

**Issue by sciurus** [mozilla/frost#397]
On master, if I run

```
$ make build-image
$ docker run localhost/frost:latest test aws/ec2/test_ec2_ebs_volume_not_piops.py 
```

I get the error

```
ERROR: usage: frost [options] [file_or_dir] [file_or_dir] [...]
frost: error: unrecognized arguments: --debug-calls
  inifile: None
  rootdir: /app
```

Based on some experimentation, I think this is because the Dockerfile runs `python setup.py install` but the frost command currently only works if you run `python setup.py develop`. Here are the steps to reproduce the problem outside of Docker:

1) Perform a fresh checkout of the frost repo
2) Run `. venv/bin/activate && pip install -U pip && pip install -r requirements.txt && python setup.py install && pre-commit install` (the standard `make install` steps, except with _install_ substituted for _develop_)
3) Run `frost test aws/ec2/test_ec2_ebs_volume_not_piops.py `
4) Observe the error "unrecognized arguments: --debug-calls"

So we need to either figure out why frost doesn't work when you run `install` or switch the Dockerfile to run `develop`.

**Comment by hwine** [comment]
I think this is a documentation issue, but I'm not sure I understand your use case.

Are you trying to:
- run "only frost" via a cli in the container?
- run "only frost" by invoking the container from your laptops cli
- simulate the automation environment?
- something else

**Comment by sciurus** [comment]
I was testing if the artifacts (python package and docker image) we are producing work as expected. My expectation is that the Docker image, which has `frost` as the ENTRYPOINT, will run that without error.

**Comment by hwine** [comment]
Ah - in that case, this is a bug with the `frost` cli -- it should return a usage message when no arguments are provided.
