### ISSUE TITLE
The test_sns_topics_without_subscriptions.py fails on orphaned SNS subscriptions.

### ISSUE THREAD

**Issue by Micheletto** [mozilla/frost#398]
Attempting to get subscription attributes on an orphaned SNS subscription will fail.  A subscription can exist without a parent topic and still be in a verified state.  SNS subscriptions without parent topics are worth identifying, because they are unusable, but this test will not indicate the correct reason for the failure.

**Comment by Micheletto** [comment]
As discussed previously: A separate test will be written for finding SNS subscriptions without parent topics, and the test_sns_pending_verified.py test will be modified to filter out tests that fail to retrieve attributes for this reason.

**Comment by Micheletto** [comment]
I think we can close this issue now.  @ajvb ?

**Comment by ajvb** [comment]
Fixed by #428
