### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by hwine** [mozilla/frost#401]
The docs currently say to "install frost from pypi", which doesn't work at this moment.

To Do:
- [x] correct docs to something that works for now (#400)
- [x] fix to install cleanly from pypi
- [ ] update docs for the new working way

**Comment by ajvb** [comment]
This is fixed, but you still will need to run `frost test` within a clone of the frost repo, as otherwise it can't find the path to test files.

**Comment by hwine** [comment]
> will need to run `frost test` within a clone of the frost repo

@ajvb Is this technically true?  E.g. do we, or do we want to, support the workflow of "once frost is installed, I just need to point it to the directory containing my tests". (that might be a phase 2 or 3 goal, or ruled out of scope)

**Comment by ajvb** [comment]
@hwine That is a good question and I'm not sure. It would be nice to support something like:

```
$ pip install frost
$ frost test -m "aws" --aws-profile my-aws-profile
```

but at the same time, this might mean that we'd have a very different flow between those that just want to run existing tests and those that want to write their own. As well, it would probably require a lot of finagling pytest to allow something like this to work.

**Comment by hwine** [comment]
I opened #411 as a separate ticket for that enhancement, and we can decide later.

I think pytest doesn't care -- assuming we can move all the "frost" configs (mostly `conftest.py`) into the "frost package", but that's work to discover.

**Comment by ajvb** [comment]
> I opened #411 as a separate ticket for that enhancement, and we can decide later.
> 
> I think pytest doesn't care -- assuming we can move all the "frost" configs (mostly `conftest.py`) into the "frost package", but that's work to discover.

As we've discussed outside of this issue, this sounds great. #411 is currently slated for 0.6.0 and the getting started docs in the README point to the currently supported path. Closing this issue.
