### ISSUE TITLE
travis-ci may no longer work reliably after 2020-12-31

### ISSUE THREAD

**Issue by hwine** [mozilla/frost#421]
The 'mozilla' org is over subscribed for OSS builds. (Builds stopped mid November for some projects.)

The recommended migrations are (in preference order):
- taskcluster
- circle-ci (paid)
- travis-ci (paid)

**Comment by ajvb** [comment]
@hwine What do you think about trying out Github Actions for Frost?

**Comment by hwine** [comment]
A lot of folks have moved to that, seemingly without any issues. I think your rust request is the only "i need x on the allow list" so far, which kinda surprised me. Pleasantly :)

**Comment by ajvb** [comment]
Ok sounds good. And yeah, even with that one, autrilla stated it should be easy to just use rust tooling directly - https://github.com/mozilla/sops/pull/792#issuecomment-755421689
