### ISSUE TITLE
Fuzzy test name and ID matchers

### ISSUE THREAD

**Issue by g-k** [mozilla/frost#67]
refs #18 #28 

It'd be handy to have fuzzier matching on test names and IDs and (maybe markers too) in the severity and exemptions config.

We might be able to reuse the pytest substring and marker matchers. Another option would be regex support.

The tricky thing would be handling multiple matching rules and avoiding accidentally adding exemptions that mask actual failures.

Alternatively, we could improve the workflow for adding exemptions (something interactive or an option to approve and output all failures for a test in the exemption config format).

**Comment by g-k** [comment]
Real world use will probably give us a better idea of how this should work.

**Comment by ajvb** [comment]
@g-k yep, real world use is confirming the need for this haha. Unless you want to work on this, I'm happy to jump on it.

**Comment by g-k** [comment]
@ajvb Go for it
